"""Stdlib-only readers for the 4 JSON index files generated by the Builder.

Production runtime code (not test fixtures) only ever READS these files —
the Builder is responsible for writing them. The runtime treats the JSON
contents as plain dicts and does not need a typed in-memory model.
"""
from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class IndexPaths:
    """Resolves the standard paths of the 4 index JSON files."""

    index_dir: Path

    @property
    def concept_index(self) -> Path:
        return self.index_dir / "concept_index.json"

    @property
    def moc_map(self) -> Path:
        return self.index_dir / "moc_map.json"

    @property
    def link_graph(self) -> Path:
        return self.index_dir / "link_graph.json"

    @property
    def alias_map(self) -> Path:
        return self.index_dir / "alias_map.json"


def load_concept_index(path: Path) -> dict[str, dict[str, Any]]:
    """Load concept_index.json. Returns dict[concept_name, entry-fields]."""
    return json.loads(path.read_text(encoding="utf-8"))


def load_moc_map(path: Path) -> dict[str, dict[str, Any]]:
    """Load moc_map.json. Returns dict[moc_name, entry-fields]."""
    return json.loads(path.read_text(encoding="utf-8"))


def load_link_graph(path: Path) -> dict[str, dict[str, Any]]:
    """Load link_graph.json. Returns dict[concept_name, link-lists]."""
    return json.loads(path.read_text(encoding="utf-8"))


def load_alias_map(path: Path) -> dict[str, str]:
    """Load alias_map.json. Returns dict[alias, canonical_concept_name]."""
    return json.loads(path.read_text(encoding="utf-8"))
