"""JSON index files: concept_index, moc_map, link_graph, alias_map.

These are immutable artifacts generated by the Builder's Emit phase
and consumed by the runtime scripts of the generated expert skill.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


@dataclass
class ConceptIndexEntry:
    """One entry in concept_index.json — maps concept name to its location & metadata."""

    path: str
    title: str
    summary: str
    tags: list[str]
    aliases: list[str]
    moc: list[str]

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "ConceptIndexEntry":
        return cls(
            path=data["path"],
            title=data["title"],
            summary=data["summary"],
            tags=list(data.get("tags", [])),
            aliases=list(data.get("aliases", [])),
            moc=list(data.get("moc", [])),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "path": self.path,
            "title": self.title,
            "summary": self.summary,
            "tags": list(self.tags),
            "aliases": list(self.aliases),
            "moc": list(self.moc),
        }


@dataclass
class ConceptIndex:
    """Maps concept name (filename stem) to its ConceptIndexEntry."""

    entries: dict[str, ConceptIndexEntry] = field(default_factory=dict)

    def __getitem__(self, name: str) -> ConceptIndexEntry:
        return self.entries[name]

    def __contains__(self, name: str) -> bool:
        return name in self.entries

    def __iter__(self):
        return iter(self.entries)

    def __len__(self) -> int:
        return len(self.entries)

    @classmethod
    def read(cls, path: Path) -> "ConceptIndex":
        raw = json.loads(path.read_text(encoding="utf-8"))
        return cls({k: ConceptIndexEntry.from_dict(v) for k, v in raw.items()})

    def write(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        serializable = {k: v.to_dict() for k, v in self.entries.items()}
        path.write_text(
            json.dumps(serializable, indent=2, sort_keys=True),
            encoding="utf-8",
        )
